# Generated by Django 2.2 on 2020-06-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caurses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
