# Generated by Django 2.2 on 2020-06-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200630_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caurses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media_root'),
        ),
    ]
